[context.production.environment]
HUGO_VERSION = "0.53"

[[headers]]
    for = "/*"
    [headers.values]
    X-FRAME-OPTIONS = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; font-src 'self' http://fonts.googleapis.com; img-src 'self' ; object-src 'none'; script-src 'self'; style-src 'self'"
    